<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnOK</name>
   <tag></tag>
   <elementGuidId>7b5afd4f-e7f9-44db-9f5a-28b28a960c83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='orangehrm-modal-footer']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='orangehrm-modal-footer']/button</value>
      <webElementGuid>49b62e9e-1338-4a1e-abba-0e7fc1277acc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
