<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPopupMessage</name>
   <tag></tag>
   <elementGuidId>4b569838-4bd4-499c-bc6b-98fc9c7066bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='orangehrm-text-center-align']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='orangehrm-text-center-align']/p</value>
      <webElementGuid>ff77bc90-5b1b-4d35-aa45-ca3f2c457ea5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
