<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnConfirm</name>
   <tag></tag>
   <elementGuidId>5e0b5385-2a0c-4757-bd0b-2a10d61984fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='orangehrm-modal-footer']/button[text()='${confirmOption}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='orangehrm-modal-footer']/button[text()='${confirmOption}']</value>
      <webElementGuid>c5ad5d57-cb4d-46ce-87c1-396dd18b6c80</webElementGuid>
   </webElementProperties>
</WebElementEntity>
