<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>colId</name>
   <tag></tag>
   <elementGuidId>96dde1bb-36cc-4a99-92a2-edccf4bbad3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//div[@role='table']/div[@class='oxd-table-header']//div[@role='columnheader'])[2]/div[@class='oxd-table-header-sort']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//div[@role='table']/div[@class='oxd-table-header']//div[@role='columnheader'])[2]/div[@class='oxd-table-header-sort']/i</value>
      <webElementGuid>08d1307a-d7d3-4e72-aae1-cb5ffde5033f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
