<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPIMPage</name>
   <tag></tag>
   <elementGuidId>639d6d1d-eb03-44a9-a907-60a8901cd08f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[text()='${fieldName}']/../following-sibling::div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[text()='${fieldName}']/../following-sibling::div//input</value>
      <webElementGuid>e7779b31-56d2-4302-bbb7-68ac72cfa728</webElementGuid>
   </webElementProperties>
</WebElementEntity>
