<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tblBodyGeneral</name>
   <tag></tag>
   <elementGuidId>e18c8006-4459-4eaa-bd29-19500b655f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role='table']/div[@class='oxd-table-body']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role='table']/div[@class='oxd-table-body']</value>
      <webElementGuid>1f34ae57-14b1-4c88-a593-f60ca1541dc8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
