<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtLeavePage</name>
   <tag></tag>
   <elementGuidId>42e97ef8-1d68-40d7-b91d-5031562758f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[text()='${fieldName}']/../following-sibling::div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[text()='${fieldName}']/../following-sibling::div//input</value>
      <webElementGuid>70662935-e37c-44fc-897c-fcfbdb47c327</webElementGuid>
   </webElementProperties>
</WebElementEntity>
